baseurl      = "localhost"
title        = "[._. ]"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Blog with programming tutorials by Dizabanik(yuh uh)"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true
  
  # Show a global language switcher in the navigation bar
  enableGlobalLanguageMenu = false

  # Metadata mostly used in document's head
  description = "Blog with programming tutorials by Dizabanik(yuh uh)"
  keywords = "homepage, blog, about"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "[._. ]"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

  [languages.en.params]
    subtitle  = "Some programming"

    [languages.en.params.logo]
      logoText = "dizabanik [._. ]"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "/about/about-me/"
  [[params.social]]
    name = "discord"
    url = "https://discordapp.com/users/546333165183303680"
  [[params.social]]
    name = "github"
    url = "https://github.com/Dizabanik"
  [[params.social]]
    name = "email"
    url = "https://mail.google.com/mail/?view=cm&fs=1&to=dizabanik@gmail.com"